In [1]:
import tensorflow as tf

print(tf.__version__)

2.0.0


In [6]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

In [7]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [8]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.24002191, -0.03332424, -0.3269905 , -0.23978993,  0.55071354,
        -0.1371544 , -0.17721656,  0.2061882 , -0.50335157,  0.34438357]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.12182916, 0.09269121, 0.06910364, 0.07540005, 0.16621986,
        0.08354985, 0.08026882, 0.11777618, 0.05793063, 0.1352306 ]],
      dtype=float32)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.4823117

In [12]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 47us/sample - loss: 0.2888 - accuracy: 0.9162
Epoch 2/5
60000/60000 [==============================] - 3s 46us/sample - loss: 0.1392 - accuracy: 0.9591
Epoch 3/5
60000/60000 [==============================] - 3s 43us/sample - loss: 0.1047 - accuracy: 0.9683
Epoch 4/5
60000/60000 [==============================] - 3s 42us/sample - loss: 0.0847 - accuracy: 0.9737
Epoch 5/5
60000/60000 [==============================] - 2s 41us/sample - loss: 0.0735 - accuracy: 0.9771


In [14]:
model.evaluate(x_test, y_test, verbose=2)

10000/1 - 0s - loss: 0.0360 - accuracy: 0.9785


[0.06976577922534198, 0.9785]

In [15]:
probability_model = tf.keras.Sequential([
    model, tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: id=30015, shape=(5, 10), dtype=float32, numpy=
array([[1.39998690e-07, 1.09598425e-07, 2.43071754e-05, 6.74947281e-04,
        2.68982978e-11, 4.74061608e-06, 1.20726400e-12, 9.99287546e-01,
        3.48165099e-06, 4.68159851e-06],
       [3.17886517e-08, 1.26459741e-03, 9.98728454e-01, 1.60590400e-06,
        5.67803115e-15, 5.23637664e-06, 1.26770544e-07, 7.78675995e-12,
        2.42450948e-08, 2.47496929e-13],
       [5.80423546e-07, 9.99342859e-01, 2.43364368e-04, 7.71040413e-06,
        3.90747082e-05, 6.07469656e-06, 9.29760517e-06, 3.05542344e-04,
        4.50287880e-05, 4.28050129e-07],
       [9.99188483e-01, 9.14287046e-09, 2.40307141e-04, 9.36814558e-07,
        3.77344418e-06, 3.99901410e-06, 1.72026539e-05, 4.73355991e-04,
        2.10491493e-07, 7.15603892e-05],
       [1.16343006e-06, 6.12263946e-08, 9.89188175e-06, 5.51805606e-08,
        9.98419046e-01, 6.58728027e-07, 8.84277233e-06, 4.30492219e-05,
        4.70072109e-06, 1.51254749e-03]], dtype=float32)>